apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"kubernetes-playground"},"name":"kubernetes-playground","namespace":"kubernetes-playground"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"kubernetes-playground"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":0},"type":"RollingUpdate"},"template":{"metadata":{"labels":{"app":"kubernetes-playground"}},"spec":{"containers":[{"env":[{"name":"KUBERNETES_PLAYGROUND_ENV","value":"production"}],"image":"localhost:5001/kubernetes-playground:1.0.0","imagePullPolicy":"IfNotPresent","lifecycle":{"postStart":{"exec":{"command":["sh","-c","echo \"Container started at $(date)\" \u003e\u003e /var/log/container.log"]}},"preStop":{"exec":{"command":["sh","-c","kill -s SIGTERM 1"]}}},"livenessProbe":{"exec":{"command":["sh","-c","test -f /var/log/container.log"]},"failureThreshold":3,"initialDelaySeconds":60,"periodSeconds":15,"successThreshold":1,"timeoutSeconds":5},"name":"kubernetes-playground","readinessProbe":{"exec":{"command":["sh","-c","test -f /var/log/container.log"]},"failureThreshold":3,"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":5},"resources":{"limits":{"cpu":"1000m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"128Mi"}},"startupProbe":{"exec":{"command":["sh","-c","test -f /var/log/container.log"]},"failureThreshold":60,"initialDelaySeconds":0,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":5},"volumeMounts":[{"mountPath":"/var/log","name":"log-volume"}]}],"terminationGracePeriodSeconds":60,"volumes":[{"emptyDir":{},"name":"log-volume"}]}}}}
  creationTimestamp: "2024-05-19T13:29:47Z"
  generation: 6
  labels:
    app: kubernetes-playground
  name: kubernetes-playground
  namespace: kubernetes-playground
  resourceVersion: "2520"
  uid: dae9549d-9d5b-4c41-a572-313730032bf7
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubernetes-playground
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubernetes-playground
    spec:
      containers:
      - env:
        - name: KUBERNETES_PLAYGROUND_ENV
          value: production
        image: localhost:5001/kubernetes-playground:1.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - echo "Container started at $(date)" >> /var/log/container.log
          preStop:
            exec:
              command:
              - sh
              - -c
              - kill -s SIGTERM 1
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - test -f /var/log/container.log
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: kubernetes-playground
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - test -f /var/log/container.log
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - test -f /var/log/container.log
          failureThreshold: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: log-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 60
      volumes:
      - emptyDir: {}
        name: log-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-05-19T13:37:42Z"
    lastUpdateTime: "2024-05-19T13:37:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-05-19T13:29:47Z"
    lastUpdateTime: "2024-05-19T13:50:07Z"
    message: ReplicaSet "kubernetes-playground-848596f5b5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
