apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-05-19T13:49:27Z"
  generateName: kubernetes-playground-848596f5b5-
  labels:
    app: kubernetes-playground
    pod-template-hash: 848596f5b5
  name: kubernetes-playground-848596f5b5-25rcd
  namespace: kubernetes-playground
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: kubernetes-playground-848596f5b5
    uid: f8c5d194-6b9c-472b-983b-74d7036327ed
  resourceVersion: "2510"
  uid: 5ca58053-1876-413f-bc1b-6c4c96c7234e
spec:
  containers:
  - env:
    - name: KUBERNETES_PLAYGROUND_ENV
      value: production
    image: localhost:5001/kubernetes-playground:1.0.0
    imagePullPolicy: IfNotPresent
    lifecycle:
      postStart:
        exec:
          command:
          - sh
          - -c
          - echo "Container started at $(date)" >> /var/log/container.log
      preStop:
        exec:
          command:
          - sh
          - -c
          - kill -s SIGTERM 1
    livenessProbe:
      exec:
        command:
        - sh
        - -c
        - test -f /var/log/container.log
      failureThreshold: 3
      initialDelaySeconds: 60
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 5
    name: kubernetes-playground
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - test -f /var/log/container.log
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        cpu: "1"
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    startupProbe:
      exec:
        command:
        - sh
        - -c
        - test -f /var/log/container.log
      failureThreshold: 60
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/log
      name: log-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-h5w55
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: kind-control-plane
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: log-volume
  - name: kube-api-access-h5w55
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-05-19T13:49:28Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-05-19T13:49:27Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-05-19T13:50:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-05-19T13:50:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-05-19T13:49:27Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://592c015b5a886b40bd3e0d3d66db5177ec09081d86a58809010064c8bdceacf8
    image: localhost:5001/kubernetes-playground:1.0.0
    imageID: localhost:5001/kubernetes-playground@sha256:b2d5f0270b991e91249b3551ca38a97239f72de0001abd04a841a9656b440183
    lastState: {}
    name: kubernetes-playground
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-05-19T13:49:28Z"
  hostIP: 172.18.0.2
  hostIPs:
  - ip: 172.18.0.2
  phase: Running
  podIP: 10.244.0.10
  podIPs:
  - ip: 10.244.0.10
  qosClass: Burstable
  startTime: "2024-05-19T13:49:27Z"
