apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubernetes-playground
  name: kubernetes-playground
  namespace: kubernetes-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes-playground
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kubernetes-playground
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - image: localhost:5001/kubernetes-playground:1.0.0
          name: kubernetes-playground
          imagePullPolicy: IfNotPresent
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - 'echo "Container started at $(date)" >> /var/log/container.log'
            preStop:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "kill -s SIGTERM 1"
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /var/log
              name: log-volume
          livenessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "test -f /var/log/container.log"
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "test -f /var/log/container.log"
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 5
          startupProbe:
            exec:
              command:
                - "sh"
                - "-c"
                - "test -f /var/log/container.log"
            initialDelaySeconds: 0
            periodSeconds: 5
            failureThreshold: 60
            successThreshold: 1
            timeoutSeconds: 5
          env:
            - name: KUBERNETES_PLAYGROUND_ENV
              value: "production"
      volumes:
        - name: log-volume
          emptyDir: {}
